apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-web-app
  template:
    metadata:
      labels:
        app: banking-web-app
    spec:
      containers:
      - name: banking-web-app
        image: akscr01sample.azurecr.io/bankapp:latest
        ports:
        - containerPort: 5171
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5171"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development" 
        - name: ConnectionStrings__DevConnection
          value: "Server=sql-server-service,1433;Database=TransactionDB;User Id=Pasupathikumar;Password=NewPassword1234;"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: banking-web-app-service
spec:
  selector:
    app: banking-web-app
  ports:
    - port: 80
      targetPort: 5171
  type: LoadBalancer
