apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-web-app
  template:
    metadata:
      labels:
        app: banking-web-app
    spec:
      containers:
      - name: banking-web-app
        image: akscr01sample.azurecr.io/bankdb:latest
        ports:
        - containerPort: 80
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "NewPassword1234"
---
apiVersion: v1
kind: Service
metadata:
  name: banking-web-app-service
spec:
  selector:
    app: banking-web-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
