apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server-container
        image: akscr01sample.azurecr.io/bankdb:latest  # Replace with your image name if different
        ports:
        - containerPort: 1433  # Exposing SQL Server port
        env:
        - name: ACCEPT_EULA
          value: "Y"  # Accept EULA for SQL Server
        - name: MSSQL_SA_PASSWORD
          value: "NewPassword1234"  # SA Password
        - name: MSSQL_PID
          value: "Express"  # Use Express edition of SQL Server
        volumeMounts:
        - name: sql-data
          mountPath: /var/opt/mssql
        readinessProbe:
          httpGet:
            path: /health  # You can also use a TCP check on port 1433 if you prefer
            port: 1433
          initialDelaySeconds: 30
          periodSeconds: 10

  volumes:
  - name: sql-data
    persistentVolumeClaim:
      claimName: sql-server-pvc  # Persistent volume claim to store database data

---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
spec:
  selector:
    app: sql-server  # This selector should match the app label of the SQL Server pod
  ports:
    - port: 1433
      targetPort: 1433  # Mapping to the SQL Server container port
  type: ClusterIP  # ClusterIP makes it available internally within the cluster
