apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-secret
              key: SA_PASSWORD
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: sql-server-data
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-server-data
        persistentVolumeClaim:
          claimName: sql-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
spec:
  selector:
    app: sql-server
  ports:
    - port: 1433
      targetPort: 1433
  type: LoadBalancer
